---
abstract: 'Caching cpandoc'
author:
  - 'tokubass <tokubass {at} cpan.org>'
build_requires:
  Capture::Tiny: '0'
  File::Temp: '0'
  Test::More: '0.98'
configure_requires:
  Module::Build::Tiny: '0.035'
dynamic_config: 0
generated_by: 'Minilla/v1.1.0, CPAN::Meta::Converter version 2.141520'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: '1.4'
name: Pod-Cpandoc-Cache
no_index:
  directory:
    - t
    - xt
    - inc
    - share
    - eg
    - examples
    - author
    - builder
provides:
  Pod::Cpandoc::Cache:
    file: lib/Pod/Cpandoc/Cache.pm
    version: '0.03'
requires:
  Class::Method::Modifiers: '0'
  Pod::Cpandoc: '0'
  Time::Piece: '1.16'
  parent: '0'
  perl: '5.008005'
resources:
  bugtracker: https://github.com/tokubass/p5-Pod-Cpandoc-Cache/issues
  homepage: https://github.com/tokubass/p5-Pod-Cpandoc-Cache
  repository: git://github.com/tokubass/p5-Pod-Cpandoc-Cache.git
version: '0.03'
x_authority: cpan:TOKUBASS
x_contributors:
  - 'tokubass <tokubass@cpan.org>'
